#define APP_TITLE "TCP-Chat by ASK60"
#define TEXT_INPUT_LABEL ""
#define SEND_LABEL "Gửi"
#define ONLINE_LIST_LABEL "Online"
#define YOU "You"
#define PUBLIC "Public"
#define LOGIN "Đăng nhập hệ thông xem điểm"
#define USERNAME "Mã số sinh viên:"
#define PASSWORD "Mật khẩu:"
#define CANCEL "Hủy"
#define LOGIN_SUCCESS "Đăng nhập thành công"
#define LOGIN_FAILED "Đăng nhập thất bại"
#define ACCOUNT_INVALID "Tài khoản hoặc mật khẩu không hợp lệ"
#define SESSION_INVALID "Tài khoản đang được đăng nhập tại máy khác sẽ bị đăng xuất"
#define WELLCOME "Chào mừng bạn đến với phần mềm chat của chúng tôi"
#define LOGOUT "Đăng xuất"
#define BUTTON_LOGIN "Đăng nhập"